from __future__ import annotations

from ai_automate_contro.ai.schemas import AI_TASK_TYPES


ALLOWED_AUTOMATION_TYPES = {"browser", "desktop"}

ACTION_TYPES: dict[str, set[str]] = {
    "variable": {"set", "set_many", "copy"},
    "page": {"open", "switch", "close"},
    "navigate": {"goto", "refresh", "back", "forward"},
    "element": {
        "click",
        "dblclick",
        "right_click",
        "hover",
        "tap",
        "fill",
        "clear",
        "type",
        "focus",
        "press",
        "check",
        "uncheck",
        "select",
        "set_files",
        "drag_to",
    },
    "wait": {"time", "selector", "url", "text", "count", "load_state", "element_state", "function"},
    "extract": {
        "text",
        "value",
        "attribute",
        "html",
        "count",
        "all_texts",
        "all_values",
        "table",
        "frames",
        "url",
        "title",
        "bounding_box",
        "css",
        "aria_snapshot",
    },
    "keyboard": {"press", "type", "down", "up"},
    "scroll": {"into_view", "by"},
    "mouse": {"move", "click", "down", "up", "wheel", "tap", "swipe"},
    "capture": {"screenshot", "html", "storage_state"},
    "dialog": {"accept", "dismiss"},
    "wait_for_network": {"request", "response"},
    "wait_for_file_chooser": {"set_files"},
    "network": {"route", "unroute", "set_extra_http_headers", "route_from_har", "route_web_socket"},
    "event": {"start", "stop", "clear"},
    "coverage": {"start", "stop", "clear"},
    "script": {"evaluate", "add_init_script"},
    "storage": {
        "cookies",
        "set_cookies",
        "clear_cookies",
        "local_storage",
        "set_local_storage",
        "remove_local_storage",
        "clear_local_storage",
        "session_storage",
        "set_session_storage",
        "remove_session_storage",
        "clear_session_storage",
    },
    "trace": {"start", "stop"},
    "trigger": {"interval"},
    "http": {"request"},
    "sql": {"query", "scalar", "execute", "executemany", "bulk_insert", "copy", "transaction"},
    "redis": {
        "get",
        "set",
        "delete",
        "hget",
        "hset",
        "hgetall",
        "lpush",
        "rpush",
        "lrange",
        "sadd",
        "smembers",
        "expire",
        "command",
        "pipeline",
    },
    "command": {"run"},
    "desktop_app": {"launch"},
    "desktop_window": {"list", "find", "active", "focus", "close", "minimize", "maximize", "restore"},
    "desktop_element": {
        "list",
        "dump",
        "find",
        "wait",
        "get_text",
        "get_state",
        "click",
        "set_text",
        "invoke",
        "select",
        "get_table",
        "select_cell",
        "get_tree",
        "expand_tree",
        "collapse_tree",
        "select_tree",
        "invoke_menu",
        "scroll_element",
    },
    "desktop_input": {"type_text", "hotkey", "click", "double_click", "right_click", "scroll", "drag"},
    "desktop_capture": {"screenshot", "snapshot", "observe"},
    "desktop_vision": {"locate_image", "locate_text"},
    "desktop_wait": {"window"},
    "desktop_assert": {"window", "screenshot", "element"},
    "table": {
        "filter",
        "select",
        "sort",
        "dedupe",
        "group",
        "join",
        "add_column",
        "rename",
        "fill_empty",
        "type_convert",
        "pivot",
    },
    "write": {"json", "text", "csv", "excel", "variables"},
    "read": {"json", "text", "csv", "excel", "storage_state"},
    "assert": {
        "selector",
        "text",
        "value",
        "url",
        "count",
        "attribute",
        "css",
        "checked",
        "unchecked",
        "enabled",
        "disabled",
        "visible",
        "hidden",
        "title",
    },
    "ai": AI_TASK_TYPES,
}

REQUIRED_FIELDS: dict[str, tuple[str, ...]] = {
    "variable": ("type",),
    "run_sub_plan": ("path",),
    "open_browser": ("name",),
    "page": ("browser", "type"),
    "close_browser": ("browser",),
    "navigate": ("browser", "type"),
    "element": ("browser", "type"),
    "wait": ("browser",),
    "detect_challenge": ("browser", "save_as"),
    "ai": ("type", "input", "save_as"),
    "extract": ("browser", "type", "save_as"),
    "keyboard": ("browser", "type"),
    "scroll": ("browser",),
    "mouse": ("browser", "type"),
    "capture": ("browser", "type", "path"),
    "manual_confirm": (),
    "print": ("message",),
    "dialog": ("type",),
    "wait_for_download": ("browser", "path", "trigger"),
    "wait_for_popup": ("browser", "popup_page", "trigger"),
    "wait_for_network": ("browser", "type", "url", "trigger"),
    "wait_for_file_chooser": ("browser", "type", "files", "trigger"),
    "network": ("browser", "type"),
    "event": ("browser", "type"),
    "coverage": ("browser", "type"),
    "script": ("browser", "type"),
    "storage": ("browser", "type"),
    "trace": ("browser", "type"),
    "write": ("type", "path"),
    "read": ("type", "path", "save_as"),
    "assert": ("browser", "type"),
    "if": ("condition",),
    "foreach": ("items", "steps"),
    "retry": ("steps",),
    "trigger": ("type", "every_seconds"),
    "http": ("type", "method", "url"),
    "sql": ("type", "connection"),
    "redis": ("type", "connection"),
    "table": ("type", "source", "save_as"),
    "command": ("type",),
    "open_desktop": ("name",),
    "close_desktop": ("desktop",),
    "desktop_app": ("desktop", "type"),
    "desktop_window": ("desktop", "type"),
    "desktop_element": ("desktop", "type"),
    "desktop_input": ("desktop", "type"),
    "desktop_capture": ("desktop", "type", "path"),
    "desktop_vision": ("desktop", "type", "path"),
    "desktop_wait": ("desktop", "type"),
    "desktop_assert": ("desktop", "type"),
    "sleep": ("seconds",),
}

OUTPUT_ACTION_CATEGORIES: dict[tuple[str, str], str] = {
    ("capture", "screenshot"): "screenshots",
    ("capture", "html"): "html",
    ("capture", "storage_state"): "storage-states",
    ("wait_for_download", ""): "downloads",
    ("trace", "stop"): "traces",
    ("event", "stop"): "json",
    ("coverage", "stop"): "json",
    ("write", "json"): "json",
    ("write", "text"): "text",
    ("write", "csv"): "csv",
    ("write", "excel"): "excel",
    ("write", "variables"): "variables",
    ("http", "request"): "http",
    ("sql", "query"): "sql",
    ("sql", "scalar"): "sql",
    ("sql", "execute"): "sql",
    ("sql", "executemany"): "sql",
    ("sql", "bulk_insert"): "sql",
    ("sql", "copy"): "sql",
    ("sql", "transaction"): "sql",
    ("redis", "get"): "redis",
    ("redis", "set"): "redis",
    ("redis", "delete"): "redis",
    ("redis", "hget"): "redis",
    ("redis", "hset"): "redis",
    ("redis", "hgetall"): "redis",
    ("redis", "lpush"): "redis",
    ("redis", "rpush"): "redis",
    ("redis", "lrange"): "redis",
    ("redis", "sadd"): "redis",
    ("redis", "smembers"): "redis",
    ("redis", "expire"): "redis",
    ("redis", "command"): "redis",
    ("redis", "pipeline"): "redis",
    ("command", "run"): "commands",
    ("desktop_window", "list"): "desktop-windows",
    ("desktop_window", "find"): "desktop-windows",
    ("desktop_window", "active"): "desktop-windows",
    ("desktop_element", "list"): "desktop-elements",
    ("desktop_element", "dump"): "desktop-elements",
    ("desktop_element", "find"): "desktop-elements",
    ("desktop_element", "wait"): "desktop-elements",
    ("desktop_element", "get_text"): "desktop-elements",
    ("desktop_element", "get_state"): "desktop-elements",
    ("desktop_element", "click"): "desktop-elements",
    ("desktop_element", "set_text"): "desktop-elements",
    ("desktop_element", "invoke"): "desktop-elements",
    ("desktop_element", "select"): "desktop-elements",
    ("desktop_element", "get_table"): "desktop-elements",
    ("desktop_element", "select_cell"): "desktop-elements",
    ("desktop_element", "get_tree"): "desktop-elements",
    ("desktop_element", "expand_tree"): "desktop-elements",
    ("desktop_element", "collapse_tree"): "desktop-elements",
    ("desktop_element", "select_tree"): "desktop-elements",
    ("desktop_element", "invoke_menu"): "desktop-elements",
    ("desktop_element", "scroll_element"): "desktop-elements",
    ("desktop_capture", "screenshot"): "desktop-screenshots",
    ("desktop_capture", "snapshot"): "desktop-state",
    ("desktop_capture", "observe"): "desktop-state",
    ("desktop_vision", "locate_image"): "desktop-vision",
    ("desktop_vision", "locate_text"): "desktop-vision",
    ("desktop_assert", "screenshot"): "desktop-screenshots",
    ("desktop_assert", "element"): "desktop-elements",
    ("ai", "connectivity"): "ai",
    ("ai", "extract_data"): "ai",
    ("ai", "classify_text"): "ai",
    ("ai", "transform_data"): "ai",
    ("ai", "summarize_text"): "ai",
}

FORBIDDEN_OUTPUT_ROOTS = {"output", "resources", "docs", "sub-plans"}

COMMON_ACTIONS = {
    "ai",
    "command",
    "foreach",
    "http",
    "if",
    "manual_confirm",
    "print",
    "read",
    "redis",
    "retry",
    "run_sub_plan",
    "sleep",
    "sql",
    "table",
    "trigger",
    "variable",
    "write",
}

BROWSER_ACTIONS = {
    "assert",
    "capture",
    "close_browser",
    "coverage",
    "detect_challenge",
    "dialog",
    "element",
    "event",
    "extract",
    "keyboard",
    "mouse",
    "navigate",
    "network",
    "open_browser",
    "page",
    "script",
    "scroll",
    "storage",
    "trace",
    "wait",
    "wait_for_download",
    "wait_for_file_chooser",
    "wait_for_network",
    "wait_for_popup",
}

DESKTOP_ACTIONS = {
    "close_desktop",
    "desktop_app",
    "desktop_capture",
    "desktop_element",
    "desktop_input",
    "desktop_vision",
    "desktop_wait",
    "desktop_assert",
    "desktop_window",
    "open_desktop",
}

ACTIONS_BY_AUTOMATION_TYPE = {
    "browser": COMMON_ACTIONS | BROWSER_ACTIONS,
    "desktop": COMMON_ACTIONS | DESKTOP_ACTIONS,
}
